"""Baseline matching model and metric evaluation functions."""

from typing import Dict, List, Set, Tuple
import pandas as pd
from src.config import PipelineConfig

def compute_composite_score(df: pd.DataFrame, config: PipelineConfig) -> pd.Series:
    """Compute transparent weighted similarity score for candidate pairs.
    
    Composite Score formula:
      name_sim = 0.5 * name_char_similarity + 0.3 * name_jaccard + 0.2 * name_exact
      address_sim = 0.5 * address_char_similarity + 0.3 * address_jaccard + 0.2 * address_exact
      country_sim = country_match
      
      score = (name_weight * name_sim) + (address_weight * address_sim) + (country_weight * country_sim)
      
    Args:
        df: Pairwise feature DataFrame.
        config: PipelineConfig containing weights.
        
    Returns:
        pd.Series of scalar scores bounded in [0.0, 1.0].
    """
    name_composite = (
        0.50 * df["name_char_similarity"] + 
        0.30 * df["name_jaccard"] + 
        0.20 * df["name_exact"]
    )
    
    address_composite = (
        0.50 * df["address_char_similarity"] + 
        0.30 * df["address_jaccard"] + 
        0.20 * df["address_exact"]
    )
    
    country_composite = df["country_match"]
    
    final_score = (
        config.name_weight * name_composite +
        config.address_weight * address_composite +
        config.country_weight * country_composite
    )
    
    return final_score

def predict_matches(features_df: pd.DataFrame, config: PipelineConfig) -> pd.DataFrame:
    """Filter candidate pairs by composite similarity threshold.
    
    Args:
        features_df: Pairwise feature DataFrame.
        config: PipelineConfig.
        
    Returns:
        Filtered DataFrame containing matches exceeding threshold:
        ['source1_entity_id', 'candidate_entity_id', 'candidate_source', 'match_score']
    """
    if features_df.empty:
        return pd.DataFrame(columns=["source1_entity_id", "candidate_entity_id", "candidate_source", "match_score"])
        
    df = features_df.copy()
    df["match_score"] = compute_composite_score(df, config)
    
    # Filter candidates by threshold
    predictions = df[df["match_score"] >= config.match_threshold].copy()
    
    return predictions[[
        "source1_entity_id", "candidate_entity_id", "candidate_source", "match_score", "blocking_rules"
    ]]

def parse_ground_truth_pairs(gt_df: pd.DataFrame) -> Set[Tuple[str, str]]:
    """Parse ground truth DataFrame into set of (source1_id, matched_id) tuples."""
    gt_pairs = set()
    for _, row in gt_df.iterrows():
        s1_id = row["entity_id"]
        matched_str = str(row["matched_entity_ids"]).strip()
        if matched_str and matched_str != "nan":
            matched_ids = [m.strip() for m in matched_str.split(",") if m.strip()]
            for m_id in matched_ids:
                gt_pairs.add((s1_id, m_id))
    return gt_pairs

def evaluate_predictions(
    candidate_pairs_df: pd.DataFrame,
    predictions_df: pd.DataFrame,
    gt_df: pd.DataFrame,
    beta: float = 0.5
) -> Dict[str, float]:
    """Evaluate candidate generation recall and final matching performance (Precision, Recall, F0.5).
    
    Args:
        candidate_pairs_df: Candidate pairs generated by blocking.
        predictions_df: Predicted matching pairs.
        gt_df: Ground truth DataFrame.
        beta: Metric parameter for F_beta (default 0.5 for F0.5 prioritizing precision).
        
    Returns:
        Dict containing candidate_recall, precision, recall, f05.
    """
    if gt_df.empty:
        return {"candidate_recall": 0.0, "precision": 0.0, "recall": 0.0, f"f{beta}": 0.0}
        
    gt_pairs = parse_ground_truth_pairs(gt_df)
    total_true_pairs = len(gt_pairs)
    
    if total_true_pairs == 0:
        return {"candidate_recall": 1.0, "precision": 1.0, "recall": 1.0, f"f{beta}": 1.0}
        
    # Candidate recall
    cand_pairs = set(zip(candidate_pairs_df["source1_entity_id"], candidate_pairs_df["candidate_entity_id"])) if not candidate_pairs_df.empty else set()
    retrieved_true_in_candidates = len(gt_pairs & cand_pairs)
    candidate_recall = retrieved_true_in_candidates / float(total_true_pairs)
    
    # Matching precision & recall
    pred_pairs = set(zip(predictions_df["source1_entity_id"], predictions_df["candidate_entity_id"])) if not predictions_df.empty else set()
    true_positives = len(gt_pairs & pred_pairs)
    false_positives = len(pred_pairs - gt_pairs)
    false_negatives = len(gt_pairs - pred_pairs)
    
    precision = true_positives / float(len(pred_pairs)) if pred_pairs else 1.0
    recall = true_positives / float(total_true_pairs)
    
    # F_beta metric calculation
    beta_sq = beta ** 2
    if precision + recall > 0:
        f_beta = (1 + beta_sq) * (precision * recall) / (beta_sq * precision + recall)
    else:
        f_beta = 0.0
        
    metrics = {
        "candidate_count": len(cand_pairs),
        "candidate_recall": candidate_recall,
        "true_positives": true_positives,
        "false_positives": false_positives,
        "false_negatives": false_negatives,
        "precision": precision,
        "recall": recall,
        f"f{beta}": f_beta
    }
    
    return metrics
